name: Docker Image CI

on:
  push:
    branches: [ master ]
#     tags:
#       - 'v*'
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1.14.0
      with: 
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0
        
    - name: Build the Docker image
      uses: docker/build-push-action@v2.9.0
      with: 
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/wedding-guest-api:latest
#       run: docker build . --file Dockerfile --tag wedding-guest-api:$(date +%s)
